* gbpdflink

Script to automatically (attempt to) add cross-references in gamebook
PDF files.

** Usage
: gbpdflink.py inbookfile.pdf resultbookfile.pdf

: optional arguments:
:  --section-format=F format of section numbers (eg "-%d-" or "Section %d")
:  --start-page=N what page in PDF to start looking for sections in

** Example

: gbpdflink.py --section-format="-%d-" somebook.pdf somebook-linked.pdf

** Dependencies
- python 2.7
- pdfminer
- pyPdf
- reportlab

** Known Required Arguments for Some Files
| file                                                     | arguments                     |
|----------------------------------------------------------+-------------------------------|
| finalpayment.pdf                                         | --start-page=7                |
| legacyofthezendari.pdf                                   | --section-format="Page %d"    |
| peledgatholthelastfortress.pdf                           | --section-format="Chapter %d" |
| thehorribledungeonsofdreadfuldoom.pdf                    | --section-format="Section %d" |
| anyportinastorm.pdf                                      | --section-format="-%d-"       |
| Holdfast_Record of the Dwarven Kingdoms_Volume 1_1.0.pdf | --section-format="-%d-"       |
| redundant.pdf                                            | --section-format="Section %d" |

** Files Known to Not Work
- fekenstein.pdf (from Windhammer Prize)
- dirtyinstruments.pdf (from Windhammer Prize)
- thescarletthief.pdf (from Windhammer Prize)
- BOOK0final.pdf (Way of The Tiger Book 0 Ninja)

** License
Copyright (c) 2013 Pelle Nilsson
All rights reserved.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
